disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Home"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"
#logo = "img/logo.png"
#secondaryLogo = "img/logo.png"
#description = "All things networking, systems, software and security"
copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "netops2devops"
image = "img/logo.png"
imageQuality = 100
headline = "All things networking, systems, software and security"
links = [
  { github = "https://github.com/netops2devops" },
  { linkedin = "https://linkedin.com/in/netops2devops" },
  { bluesky = "https://bsky.app/profile/netops2devops.net" },
  #{ codeberg = "https://codeberg.org/netops2devops"}
]
